### ISSUE TITLE
Datasets and algorithms.

### ISSUE THREAD

**Issue by benedekrozemberczki** [ikenna-oluigbo/machinelearningtasks#1]
1. I have a feeling that most of the algorithms that you analyze use my implementations from Karate Club. I would consider adding this as a citation:

@misc{karateclub2020,
      title={An API Oriented Open-source Python Framework for Unsupervised Learning on Graphs},
      author={Benedek Rozemberczki and Oliver Kiss and Rik Sarkar},
      year={2020},
      eprint={2003.04819},
      archivePrefix={arXiv},
      primaryClass={cs.LG}
}

2. The GEMSEC Facebook News Sites dataset can be cited as:

  @inproceedings{rozemberczki2019gemsec,    
    title={GEMSEC: Graph Embedding with Self Clustering},    
    author={Rozemberczki, Benedek and Davies, Ryan and Sarkar, Rik and Sutton, Charles},    
    booktitle={Proceedings of the 2019 IEEE/ACM International Conference on Advances in Social Networks Analysis and Mining 2019},    
    pages={65-72},    
    year={2019},    
    organization={ACM}    
    }

**Comment by ikenna-oluigbo** [comment]
Hello, 
The work is still under review with a journal. 
The documentation (will would be uploaded soon) contains the relevant citations for all datasets and algorithms used in the study. The GEMSEC Facebook News Sites dataset was duly cited. 

Thanks and Regards.
